package com.example

data class EmojiItem(val emoji: String, val tags: List<String>)

object EmojiDataSource {
    val categories = listOf(
        "Recent",
        "Smileys",
        "People",
        "Animals",
        "Food",
        "Travel",
        "Activities",
        "Objects",
        "Symbols",
        "Flags"
    )

    val emojiData: Map<String, List<EmojiItem>> = mapOf(
        "Smileys" to listOf(
            EmojiItem("😀", listOf("smile", "happy", "grin")),
            EmojiItem("😃", listOf("smile", "happy", "grin", "open mouth")),
            EmojiItem("😄", listOf("smile", "happy", "grin", "eye")),
            EmojiItem("😁", listOf("grin", "happy", "smile", "beaming")),
            EmojiItem("😆", listOf("laugh", "happy", "smile", "squint")),
            EmojiItem("😅", listOf("smile", "sweat", "happy", "relief")),
            EmojiItem("🤣", listOf("laugh", "funny", "rofl")),
            EmojiItem("😂", listOf("laugh", "cry", "joy", "funny")),
            EmojiItem("🙂", listOf("smile", "slight")),
            EmojiItem("🙃", listOf("upside down", "sarcastic")),
            EmojiItem("😉", listOf("wink", "happy")),
            EmojiItem("😊", listOf("smile", "blush", "happy")),
            EmojiItem("😇", listOf("angel", "halo", "innocent")),
            EmojiItem("🥰", listOf("loving", "hearts", "blush")),
            EmojiItem("😍", listOf("love", "heart", "eyes")),
            EmojiItem("🤩", listOf("star", "eyes", "excited")),
            EmojiItem("😘", listOf("kiss", "love", "heart")),
            EmojiItem("😗", listOf("kiss")),
            EmojiItem("☺️", listOf("smile")),
            EmojiItem("😚", listOf("kiss", "closed eyes")),
            EmojiItem("😙", listOf("kiss", "smiling eyes")),
            EmojiItem("😋", listOf("yum", "delicious", "tongue")),
            EmojiItem("😛", listOf("tongue", "stuck out")),
            EmojiItem("😜", listOf("tongue", "wink")),
            EmojiItem("🤪", listOf("zany", "crazy", "goofy")),
            EmojiItem("😝", listOf("tongue", "squint")),
            EmojiItem("🤑", listOf("money", "rich")),
            EmojiItem("🤗", listOf("hug", "happy")),
            EmojiItem("🤭", listOf("giggle", "laugh", "secret")),
            EmojiItem("🤫", listOf("shh", "quiet")),
            EmojiItem("🤔", listOf("think", "hmm")),
            EmojiItem("🤐", listOf("zipper", "secret")),
            EmojiItem("🤨", listOf("eyebrow", "skeptical")),
            EmojiItem("😐", listOf("neutral", "straight")),
            EmojiItem("😑", listOf("expressionless")),
            EmojiItem("😶", listOf("no mouth", "silent")),
            EmojiItem("😏", listOf("smirk", "sly")),
            EmojiItem("😒", listOf("unimpressed", "annoyed")),
            EmojiItem("🙄", listOf("eyeroll", "annoyed")),
            EmojiItem("😬", listOf("grimace", "awkward")),
            EmojiItem("🤥", listOf("lie", "pinocchio")),
            EmojiItem("😌", listOf("relieved", "calm")),
            EmojiItem("😔", listOf("pensive", "sad")),
            EmojiItem("😪", listOf("sleepy")),
            EmojiItem("🤤", listOf("drool")),
            EmojiItem("😴", listOf("sleep", "zzz")),
            EmojiItem("😷", listOf("mask", "sick")),
            EmojiItem("🤒", listOf("fever", "sick")),
            EmojiItem("🤕", listOf("bandage", "sick")),
            EmojiItem("🤢", listOf("nauseated", "sick")),
            EmojiItem("🤮", listOf("puke", "vomit")),
            EmojiItem("🤧", listOf("sneeze", "cold")),
            EmojiItem("🥵", listOf("hot", "sweat")),
            EmojiItem("🥶", listOf("cold", "blue")),
            EmojiItem("🥴", listOf("drunk", "dizzy")),
            EmojiItem("😵", listOf("dizzy", "dead")),
            EmojiItem("🤯", listOf("mind blown", "boom")),
            EmojiItem("🤠", listOf("cowboy", "hat")),
            EmojiItem("🥳", listOf("party", "celebrate")),
            EmojiItem("😎", listOf("cool", "sunglasses")),
            EmojiItem("🤓", listOf("nerd", "geek")),
            EmojiItem("🧐", listOf("monocle", "smart")),
            EmojiItem("😕", listOf("confused", "puzzled")),
            EmojiItem("😟", listOf("worried")),
            EmojiItem("🙁", listOf("frown", "sad")),
            EmojiItem("😮", listOf("shock", "open")),
            EmojiItem("😯", listOf("hush", "shock")),
            EmojiItem("😲", listOf("astonished", "wow")),
            EmojiItem("😳", listOf("blush", "shocked")),
            EmojiItem("🥺", listOf("pleading", "cute")),
            EmojiItem("😦", listOf("frowning", "open")),
            EmojiItem("😧", listOf("anguished")),
            EmojiItem("😨", listOf("fear", "scared")),
            EmojiItem("😰", listOf("anxious", "sweat")),
            EmojiItem("😥", listOf("sad", "relief")),
            EmojiItem("😢", listOf("cry", "sad")),
            EmojiItem("😭", listOf("sob", "cry", "sad")),
            EmojiItem("😱", listOf("scream", "scared")),
            EmojiItem("😖", listOf("confounded")),
            EmojiItem("😣", listOf("persevering")),
            EmojiItem("😞", listOf("disappointed", "sad")),
            EmojiItem("😓", listOf("sweat", "sad")),
            EmojiItem("😩", listOf("weary", "tired")),
            EmojiItem("😫", listOf("tired")),
            EmojiItem("🥱", listOf("yawn", "tired")),
            EmojiItem("😤", listOf("angry", "steam")),
            EmojiItem("😡", listOf("angry", "pout")),
            EmojiItem("😠", listOf("angry")),
            EmojiItem("🤬", listOf("angry", "swearing")),
            EmojiItem("😈", listOf("devil", "evil")),
            EmojiItem("👿", listOf("imp", "evil")),
            EmojiItem("💀", listOf("skull", "dead")),
            EmojiItem("☠️", listOf("crossbones", "dead")),
            EmojiItem("💩", listOf("poop", "funny")),
            EmojiItem("🤡", listOf("clown", "funny")),
            EmojiItem("👹", listOf("ogre", "scary")),
            EmojiItem("👺", listOf("goblin", "scary")),
            EmojiItem("👻", listOf("ghost", "scary")),
            EmojiItem("👽", listOf("alien", "outer space")),
            EmojiItem("👾", listOf("alien", "monster")),
            EmojiItem("🤖", listOf("robot", "bot"))
        ),
        "People" to listOf(
            EmojiItem("👋", listOf("wave", "hello")),
            EmojiItem("🤚", listOf("back of hand")),
            EmojiItem("🖐️", listOf("hand", "expanded fingers")),
            EmojiItem("✋", listOf("high five", "hand")),
            EmojiItem("🖖", listOf("vulcan", "star trek")),
            EmojiItem("👌", listOf("ok", "good")),
            EmojiItem("🤌", listOf("pinched fingers", "italian")),
            EmojiItem("🤏", listOf("pinched hand")),
            EmojiItem("✌️", listOf("victory", "peace")),
            EmojiItem("🤞", listOf("luck", "fingers crossed")),
            EmojiItem("🤟", listOf("iloveyou", "love")),
            EmojiItem("🤘", listOf("rock on")),
            EmojiItem("🤙", listOf("call me")),
            EmojiItem("👈", listOf("point left")),
            EmojiItem("👉", listOf("point right")),
            EmojiItem("👆", listOf("point up")),
            EmojiItem("🖕", listOf("middle finger")),
            EmojiItem("👇", listOf("point down")),
            EmojiItem("☝️", listOf("index up")),
            EmojiItem("👍", listOf("thumbs up", "good")),
            EmojiItem("👎", listOf("thumbs down", "bad")),
            EmojiItem("✊", listOf("fist", "power")),
            EmojiItem("👊", listOf("oncoming fist", "punch")),
            EmojiItem("🤛", listOf("left fist")),
            EmojiItem("🤜", listOf("right fist")),
            EmojiItem("👏", listOf("clap", "bravo")),
            EmojiItem("🙌", listOf("hands", "celebrate")),
            EmojiItem("👐", listOf("open hands")),
            EmojiItem("🤲", listOf("palms up")),
            EmojiItem("🤝", listOf("handshake", "deal")),
            EmojiItem("🙏", listOf("pray", "thank you")),
            EmojiItem("✍️", listOf("write")),
            EmojiItem("💅", listOf("nail polish", "beauty")),
            EmojiItem("🤳", listOf("selfie", "phone")),
            EmojiItem("💪", listOf("flex", "strong")),
            EmojiItem("🦾", listOf("mechanical arm")),
            EmojiItem("🦿", listOf("mechanical leg")),
            EmojiItem("🦵", listOf("leg")),
            EmojiItem("🦶", listOf("foot")),
            EmojiItem("👂", listOf("ear")),
            EmojiItem("🦻", listOf("hearing aid")),
            EmojiItem("👃", listOf("nose")),
            EmojiItem("🧠", listOf("brain", "smart")),
            EmojiItem("🫀", listOf("heart", "organ")),
            EmojiItem("🫁", listOf("lungs")),
            EmojiItem("🦷", listOf("tooth")),
            EmojiItem("🦴", listOf("bone")),
            EmojiItem("👀", listOf("eyes", "look")),
            EmojiItem("👁️", listOf("eye")),
            EmojiItem("👅", listOf("tongue")),
            EmojiItem("👄", listOf("mouth", "lips")),
            EmojiItem("👶", listOf("baby", "child")),
            EmojiItem("🧒", listOf("child")),
            EmojiItem("👦", listOf("boy")),
            EmojiItem("👧", listOf("girl")),
            EmojiItem("🧑", listOf("person")),
            EmojiItem("👱", listOf("person", "blond")),
            EmojiItem("👨", listOf("man")),
            EmojiItem("🧔", listOf("beard", "man")),
            EmojiItem("👩", listOf("woman")),
            EmojiItem("🧓", listOf("older person")),
            EmojiItem("👴", listOf("old man")),
            EmojiItem("👵", listOf("old woman")),
            EmojiItem("👮", listOf("police", "cop")),
            EmojiItem("👩‍🚒", listOf("firefighter")),
            EmojiItem("👨‍✈️", listOf("pilot")),
            EmojiItem("👩‍🍳", listOf("cook", "chef")),
            EmojiItem("👨‍🎓", listOf("student", "graduate")),
            EmojiItem("🕵️", listOf("detective")),
            EmojiItem("💂", listOf("guard")),
            EmojiItem("👷", listOf("construction")),
            EmojiItem("🤴", listOf("prince")),
            EmojiItem("👸", listOf("princess")),
            EmojiItem("👰", listOf("bride")),
            EmojiItem("🤵", listOf("groom")),
            EmojiItem("🤰", listOf("pregnant")),
            EmojiItem("🤱", listOf("breastfeeding")),
            EmojiItem("👼", listOf("baby angel")),
            EmojiItem("🎅", listOf("santa")),
            EmojiItem("🤶", listOf("mrs claus")),
            EmojiItem("🦸", listOf("superhero")),
            EmojiItem("🦹", listOf("supervillain")),
            EmojiItem("🧙", listOf("mage", "wizard")),
            EmojiItem("🧚", listOf("fairy")),
            EmojiItem("🧛", listOf("vampire")),
            EmojiItem("🧜", listOf("merperson")),
            EmojiItem("🧝", listOf("elf")),
            EmojiItem("🧞", listOf("genie")),
            EmojiItem("🧟", listOf("zombie")),
            EmojiItem("💆", listOf("massage")),
            EmojiItem("💇", listOf("haircut")),
            EmojiItem("🚶", listOf("walking")),
            EmojiItem("🏃", listOf("running")),
            EmojiItem("💃", listOf("dancing", "woman")),
            EmojiItem("🕺", listOf("dancing", "man")),
            EmojiItem("👯", listOf("people dancing"))
        ),
        "Animals" to listOf(
            EmojiItem("🐵", listOf("monkey face")),
            EmojiItem("🐒", listOf("monkey")),
            EmojiItem("🦍", listOf("gorilla")),
            EmojiItem("🦧", listOf("orangutan")),
            EmojiItem("🐶", listOf("dog face")),
            EmojiItem("🐕", listOf("dog")),
            EmojiItem("🦮", listOf("guide dog")),
            EmojiItem("🐩", listOf("poodle")),
            EmojiItem("🐺", listOf("wolf")),
            EmojiItem("🦊", listOf("fox")),
            EmojiItem("🦝", listOf("raccoon")),
            EmojiItem("🐱", listOf("cat face")),
            EmojiItem("🐈", listOf("cat")),
            EmojiItem("🦁", listOf("lion")),
            EmojiItem("🐯", listOf("tiger face")),
            EmojiItem("🐅", listOf("tiger")),
            EmojiItem("🐆", listOf("leopard")),
            EmojiItem("🐴", listOf("horse face")),
            EmojiItem("🐎", listOf("horse")),
            EmojiItem("🦄", listOf("unicorn")),
            EmojiItem("🦓", listOf("zebra")),
            EmojiItem("🦌", listOf("deer")),
            EmojiItem("🦬", listOf("bison")),
            EmojiItem("🐮", listOf("cow face")),
            EmojiItem("🐂", listOf("ox")),
            EmojiItem("🐃", listOf("water buffalo")),
            EmojiItem("🐄", listOf("cow")),
            EmojiItem("🐷", listOf("pig face")),
            EmojiItem("🐖", listOf("pig")),
            EmojiItem("🐗", listOf("boar")),
            EmojiItem("🐽", listOf("pig nose")),
            EmojiItem("🐏", listOf("ram")),
            EmojiItem("🐑", listOf("ewe", "sheep")),
            EmojiItem("🐐", listOf("goat")),
            EmojiItem("🐪", listOf("camel")),
            EmojiItem("🐫", listOf("two-hump camel")),
            EmojiItem("🦙", listOf("llama")),
            EmojiItem("🦒", listOf("giraffe")),
            EmojiItem("🐘", listOf("elephant")),
            EmojiItem("🦣", listOf("mammoth")),
            EmojiItem("🦏", listOf("rhinoceros")),
            EmojiItem("🦛", listOf("hippopotamus")),
            EmojiItem("🐭", listOf("mouse face")),
            EmojiItem("🖱️", listOf("mouse")),
            EmojiItem("🐀", listOf("rat")),
            EmojiItem("🐹", listOf("hamster")),
            EmojiItem("🐰", listOf("rabbit face")),
            EmojiItem("🐇", listOf("rabbit")),
            EmojiItem("🐿️", listOf("chipmunk")),
            EmojiItem("🦫", listOf("beaver")),
            EmojiItem("🦔", listOf("hedgehog")),
            EmojiItem("🦇", listOf("bat")),
            EmojiItem("🐻", listOf("bear")),
            EmojiItem("🐨", listOf("koala")),
            EmojiItem("🐼", listOf("panda")),
            EmojiItem("🦥", listOf("sloth")),
            EmojiItem("🦦", listOf("otter")),
            EmojiItem("🦨", listOf("skunk")),
            EmojiItem("🦘", listOf("kangaroo")),
            EmojiItem("🦡", listOf("badger")),
            EmojiItem("🐾", listOf("paw")),
            EmojiItem("🦃", listOf("turkey")),
            EmojiItem("🐔", listOf("chicken")),
            EmojiItem("🐓", listOf("rooster")),
            EmojiItem("🐣", listOf("hatching chick")),
            EmojiItem("🐥", listOf("baby chick")),
            EmojiItem("🐦", listOf("bird")),
            EmojiItem("🐧", listOf("penguin")),
            EmojiItem("🕊️", listOf("dove")),
            EmojiItem("🦅", listOf("eagle")),
            EmojiItem("🦆", listOf("duck")),
            EmojiItem("🦢", listOf("swan")),
            EmojiItem("🦉", listOf("owl")),
            EmojiItem("🦤", listOf("dodo")),
            EmojiItem("🪶", listOf("feather")),
            EmojiItem("🦩", listOf("flamingo")),
            EmojiItem("🦚", listOf("peacock")),
            EmojiItem("🦜", listOf("parrot")),
            EmojiItem("🐸", listOf("frog")),
            EmojiItem("🐊", listOf("crocodile")),
            EmojiItem("🐢", listOf("turtle")),
            EmojiItem("🦎", listOf("lizard")),
            EmojiItem("🐍", listOf("snake")),
            EmojiItem("🐲", listOf("dragon face")),
            EmojiItem("🐉", listOf("dragon")),
            EmojiItem("🦕", listOf("sauropod")),
            EmojiItem("🦖", listOf("t-rex")),
            EmojiItem("🐳", listOf("spouting whale")),
            EmojiItem("🐋", listOf("whale")),
            EmojiItem("🐬", listOf("dolphin")),
            EmojiItem("🦭", listOf("seal")),
            EmojiItem("🐟", listOf("fish")),
            EmojiItem("🐠", listOf("tropical fish")),
            EmojiItem("🐡", listOf("blowfish")),
            EmojiItem("🦈", listOf("shark")),
            EmojiItem("🐙", listOf("octopus")),
            EmojiItem("🐚", listOf("spiral shell")),
            EmojiItem("🐌", listOf("snail")),
            EmojiItem("🦋", listOf("butterfly")),
            EmojiItem("🐛", listOf("bug")),
            EmojiItem("🐜", listOf("ant")),
            EmojiItem("🐝", listOf("honeybee")),
            EmojiItem("🪲", listOf("beetle")),
            EmojiItem("🐞", listOf("lady beetle")),
            EmojiItem("🦗", listOf("cricket")),
            EmojiItem("🪳", listOf("cockroach")),
            EmojiItem("🕷️", listOf("spider")),
            EmojiItem("🕸️", listOf("spider web")),
            EmojiItem("🦂", listOf("scorpion")),
            EmojiItem("🦟", listOf("mosquito")),
            EmojiItem("🪰", listOf("fly")),
            EmojiItem("🪱", listOf("worm")),
            EmojiItem("🦠", listOf("microbe"))
        ),
        "Food" to listOf(
            EmojiItem("🍏", listOf("green apple")),
            EmojiItem("🍎", listOf("red apple")),
            EmojiItem("🍐", listOf("pear")),
            EmojiItem("🍊", listOf("tangerine")),
            EmojiItem("🍋", listOf("lemon")),
            EmojiItem("🍌", listOf("banana")),
            EmojiItem("🍉", listOf("watermelon")),
            EmojiItem("🍇", listOf("grapes")),
            EmojiItem("🍓", listOf("strawberry")),
            EmojiItem("🫐", listOf("blueberries")),
            EmojiItem("🍈", listOf("melon")),
            EmojiItem("🍒", listOf("cherries")),
            EmojiItem("🍑", listOf("peach")),
            EmojiItem("🥭", listOf("mango")),
            EmojiItem("🍍", listOf("pineapple")),
            EmojiItem("🥥", listOf("coconut")),
            EmojiItem("🥝", listOf("kiwi fruit")),
            EmojiItem("🍅", listOf("tomato")),
            EmojiItem("🍆", listOf("eggplant")),
            EmojiItem("🥑", listOf("avocado")),
            EmojiItem("🥦", listOf("broccoli")),
            EmojiItem("🥬", listOf("leafy green")),
            EmojiItem("🥒", listOf("cucumber")),
            EmojiItem("🌶️", listOf("hot pepper")),
            EmojiItem("🫑", listOf("bell pepper")),
            EmojiItem("🌽", listOf("ear of corn")),
            EmojiItem("🥕", listOf("carrot")),
            EmojiItem("🫒", listOf("olive")),
            EmojiItem("🧄", listOf("garlic")),
            EmojiItem("🧅", listOf("onion")),
            EmojiItem("🍄", listOf("mushroom")),
            EmojiItem("🥜", listOf("peanuts")),
            EmojiItem("🫘", listOf("beans")),
            EmojiItem("🌰", listOf("chestnut")),
            EmojiItem("🍞", listOf("bread")),
            EmojiItem("🥐", listOf("croissant")),
            EmojiItem("🥖", listOf("baguette bread")),
            EmojiItem("🫓", listOf("flatbread")),
            EmojiItem("🥨", listOf("pretzel")),
            EmojiItem("🥯", listOf("bagel")),
            EmojiItem("🥞", listOf("pancakes")),
            EmojiItem("🧇", listOf("waffle")),
            EmojiItem("🧀", listOf("cheese wedge")),
            EmojiItem("🍖", listOf("meat on bone")),
            EmojiItem("🍗", listOf("poultry leg")),
            EmojiItem("🥩", listOf("cut of meat")),
            EmojiItem("🥓", listOf("bacon")),
            EmojiItem("🍔", listOf("hamburger")),
            EmojiItem("🍟", listOf("french fries")),
            EmojiItem("🍕", listOf("pizza")),
            EmojiItem("🌭", listOf("hot dog")),
            EmojiItem("🥪", listOf("sandwich")),
            EmojiItem("🌮", listOf("taco")),
            EmojiItem("🌯", listOf("burrito")),
            EmojiItem("🫔", listOf("tamale")),
            EmojiItem("🥙", listOf("stuffed flatbread")),
            EmojiItem("🧆", listOf("falafel")),
            EmojiItem("🥚", listOf("egg")),
            EmojiItem("🍳", listOf("cooking")),
            EmojiItem("🥘", listOf("shallow pan of food")),
            EmojiItem("🍲", listOf("pot of food")),
            EmojiItem("🫕", listOf("fondue")),
            EmojiItem("🥣", listOf("bowl with spoon")),
            EmojiItem("🥗", listOf("green salad")),
            EmojiItem("🍿", listOf("popcorn")),
            EmojiItem("🧈", listOf("butter")),
            EmojiItem("🧂", listOf("salt")),
            EmojiItem("🥫", listOf("canned food")),
            EmojiItem("🍱", listOf("bento box")),
            EmojiItem("🍘", listOf("rice cracker")),
            EmojiItem("🍙", listOf("rice ball")),
            EmojiItem("🍚", listOf("cooked rice")),
            EmojiItem("🍛", listOf("curry rice")),
            EmojiItem("🍜", listOf("steaming bowl")),
            EmojiItem("🍝", listOf("spaghetti")),
            EmojiItem("🍠", listOf("roasted sweet potato")),
            EmojiItem("🍢", listOf("oden")),
            EmojiItem("🍣", listOf("sushi")),
            EmojiItem("🍤", listOf("fried shrimp")),
            EmojiItem("🍥", listOf("fish cake with swirl")),
            EmojiItem("🥮", listOf("moon cake")),
            EmojiItem("🍡", listOf("dango")),
            EmojiItem("🥟", listOf("dumpling")),
            EmojiItem("🥠", listOf("fortune cookie")),
            EmojiItem("🥡", listOf("takeout box")),
            EmojiItem("🍦", listOf("soft serve")),
            EmojiItem("🍧", listOf("shaved ice")),
            EmojiItem("🍨", listOf("ice cream")),
            EmojiItem("🍩", listOf("doughnut")),
            EmojiItem("🍪", listOf("cookie")),
            EmojiItem("🎂", listOf("birthday cake")),
            EmojiItem("🍰", listOf("shortcake")),
            EmojiItem("🧁", listOf("cupcake")),
            EmojiItem("🥧", listOf("pie")),
            EmojiItem("🍫", listOf("chocolate bar")),
            EmojiItem("🍬", listOf("candy")),
            EmojiItem("🍭", listOf("lollipop")),
            EmojiItem("🍮", listOf("custard")),
            EmojiItem("🍯", listOf("honey pot")),
            EmojiItem("🍼", listOf("baby bottle")),
            EmojiItem("🥛", listOf("glass of milk")),
            EmojiItem("☕", listOf("hot beverage")),
            EmojiItem("🫖", listOf("teapot")),
            EmojiItem("🍵", listOf("teacup without handle")),
            EmojiItem("🍶", listOf("sake")),
            EmojiItem("🍾", listOf("bottle with popping cork")),
            EmojiItem("🍷", listOf("wine glass")),
            EmojiItem("🍸", listOf("cocktail glass")),
            EmojiItem("🍹", listOf("tropical drink")),
            EmojiItem("🍺", listOf("beer mug")),
            EmojiItem("🍻", listOf("clinking beer mugs")),
            EmojiItem("🥂", listOf("clinking glasses")),
            EmojiItem("🥃", listOf("tumbler glass")),
            EmojiItem("🥤", listOf("cup with straw")),
            EmojiItem("🧋", listOf("bubble tea")),
            EmojiItem("🧃", listOf("beverage box")),
            EmojiItem("🧉", listOf("mate")),
            EmojiItem("🧊", listOf("ice cube"))
        ),
        "Travel" to listOf(
            EmojiItem("🌍", listOf("earth globe europe-africa")),
            EmojiItem("🌎", listOf("earth globe americas")),
            EmojiItem("🌏", listOf("earth globe asia-australia")),
            EmojiItem("🌐", listOf("globe with meridians")),
            EmojiItem("🗺️", listOf("world map")),
            EmojiItem("🗾", listOf("map of japan")),
            EmojiItem("🧭", listOf("compass")),
            EmojiItem("🏔️", listOf("snow-capped mountain")),
            EmojiItem("⛰️", listOf("mountain")),
            EmojiItem("🌋", listOf("volcano")),
            EmojiItem("🗻", listOf("mount fuji")),
            EmojiItem("🏕️", listOf("camping")),
            EmojiItem("🏖️", listOf("beach with umbrella")),
            EmojiItem("🏜️", listOf("desert")),
            EmojiItem("🏝️", listOf("desert island")),
            EmojiItem("🏞️", listOf("national park")),
            EmojiItem("🏟️", listOf("stadium")),
            EmojiItem("🏛️", listOf("classical building")),
            EmojiItem("🏗️", listOf("building construction")),
            EmojiItem("🧱", listOf("brick")),
            EmojiItem("🏘️", listOf("houses")),
            EmojiItem("🏚️", listOf("derelict house")),
            EmojiItem("🏠", listOf("house")),
            EmojiItem("🏡", listOf("house with garden")),
            EmojiItem("🏢", listOf("office building")),
            EmojiItem("🏣", listOf("japanese post office")),
            EmojiItem("🏤", listOf("post office")),
            EmojiItem("🏥", listOf("hospital")),
            EmojiItem("🏦", listOf("bank")),
            EmojiItem("🏨", listOf("hotel")),
            EmojiItem("🏩", listOf("love hotel")),
            EmojiItem("🏪", listOf("convenience store")),
            EmojiItem("🏫", listOf("school")),
            EmojiItem("🏬", listOf("department store")),
            EmojiItem("🏭", listOf("factory")),
            EmojiItem("🏮", listOf("red paper lantern")),
            EmojiItem("🏯", listOf("japanese castle")),
            EmojiItem("🏰", listOf("castle")),
            EmojiItem("💒", listOf("wedding")),
            EmojiItem("🗼", listOf("tokyo tower")),
            EmojiItem("🗽", listOf("statue of liberty")),
            EmojiItem("⛪", listOf("church")),
            EmojiItem("🕌", listOf("mosque")),
            EmojiItem("🛕", listOf("hindu temple")),
            EmojiItem("🕍", listOf("synagogue")),
            EmojiItem("⛩️", listOf("shinto shrine")),
            EmojiItem("🕋", listOf("kaaba")),
            EmojiItem("⛲", listOf("fountain")),
            EmojiItem("⛺", listOf("tent")),
            EmojiItem("🌁", listOf("foggy")),
            EmojiItem("🌃", listOf("night with stars")),
            EmojiItem("🏙️", listOf("cityscape")),
            EmojiItem("🌅", listOf("sunrise")),
            EmojiItem("🌄", listOf("sunrise over mountains")),
            EmojiItem("🌇", listOf("sunset")),
            EmojiItem("🌆", listOf("cityscape at dusk")),
            EmojiItem("🌉", listOf("bridge at night")),
            EmojiItem("🏙️", listOf("cityscape")),
            EmojiItem("♨️", listOf("hot springs")),
            EmojiItem("🎠", listOf("carousel horse")),
            EmojiItem("🎡", listOf("ferris wheel")),
            EmojiItem("🎢", listOf("roller coaster")),
            EmojiItem("💈", listOf("barber pole")),
            EmojiItem("🎪", listOf("circus tent")),
            EmojiItem("🚂", listOf("locomotive")),
            EmojiItem("🚃", listOf("railway car")),
            EmojiItem("🚄", listOf("high-speed train")),
            EmojiItem("🚅", listOf("bullet train")),
            EmojiItem("🚆", listOf("train")),
            EmojiItem("🚇", listOf("metro")),
            EmojiItem("🚈", listOf("light rail")),
            EmojiItem("🚉", listOf("station")),
            EmojiItem("🚊", listOf("tram")),
            EmojiItem("🚝", listOf("monorail")),
            EmojiItem("🚞", listOf("mountain railway")),
            EmojiItem("🚋", listOf("tram car")),
            EmojiItem("🚌", listOf("bus")),
            EmojiItem("🚍", listOf("oncoming bus")),
            EmojiItem("🚎", listOf("trolleybus")),
            EmojiItem("🚐", listOf("minibus")),
            EmojiItem("🚑", listOf("ambulance")),
            EmojiItem("🚒", listOf("fire engine")),
            EmojiItem("🚓", listOf("police car")),
            EmojiItem("🚔", listOf("oncoming police car")),
            EmojiItem("🚕", listOf("taxi")),
            EmojiItem("🚖", listOf("oncoming taxi")),
            EmojiItem("🚗", listOf("automobile")),
            EmojiItem("🚘", listOf("oncoming automobile")),
            EmojiItem("🚙", listOf("sport utility vehicle")),
            EmojiItem("🚚", listOf("delivery truck")),
            EmojiItem("🚛", listOf("articulated lorry")),
            EmojiItem("🚜", listOf("tractor")),
            EmojiItem("🏎️", listOf("racing car")),
            EmojiItem("🏍️", listOf("motorcycle")),
            EmojiItem("🛵", listOf("motor scooter")),
            EmojiItem("🦽", listOf("manual wheelchair")),
            EmojiItem("🦼", listOf("motorized wheelchair")),
            EmojiItem("🛴", listOf("kick scooter")),
            EmojiItem("🚲", listOf("bicycle")),
            EmojiItem("🛵", listOf("motor scooter")),
            EmojiItem("🛺", listOf("auto rickshaw")),
            EmojiItem("🚍", listOf("oncoming bus")),
            EmojiItem("🚏", listOf("bus stop")),
            EmojiItem("🛣️", listOf("motorway")),
            EmojiItem("🛤️", listOf("railway track")),
            EmojiItem("⛽", listOf("fuel pump")),
            EmojiItem("🚨", listOf("police car light")),
            EmojiItem("🚥", listOf("horizontal traffic light")),
            EmojiItem("🚦", listOf("vertical traffic light")),
            EmojiItem("🛑", listOf("stop sign")),
            EmojiItem("🚧", listOf("construction")),
            EmojiItem("⚓", listOf("anchor")),
            EmojiItem("⛵", listOf("sailboat")),
            EmojiItem("🛶", listOf("canoe")),
            EmojiItem("🚤", listOf("speedboat")),
            EmojiItem("🛳️", listOf("passenger ship")),
            EmojiItem("⛴️", listOf("ferry")),
            EmojiItem("🛥️", listOf("motor boat")),
            EmojiItem("🚢", listOf("ship")),
            EmojiItem("✈️", listOf("airplane")),
            EmojiItem("🛫", listOf("airplane departure")),
            EmojiItem("🛬", listOf("airplane arrival")),
            EmojiItem("💺", listOf("seat")),
            EmojiItem("🚁", listOf("helicopter")),
            EmojiItem("🚟", listOf("suspension railway")),
            EmojiItem("🚠", listOf("mountain cableway")),
            EmojiItem("🚡", listOf("aerial tramway")),
            EmojiItem("🚀", listOf("rocket")),
            EmojiItem("🛸", listOf("flying saucer")),
            EmojiItem("🌠", listOf("shooting star")),
            EmojiItem("🌌", listOf("milky way")),
            EmojiItem("🌙", listOf("crescent moon")),
            EmojiItem("🌑", listOf("new moon")),
            EmojiItem("🌕", listOf("full moon")),
            EmojiItem("☀️", listOf("sun")),
            EmojiItem("🌞", listOf("sun with face")),
            EmojiItem("⭐", listOf("star")),
            EmojiItem("🌟", listOf("glowing star")),
            EmojiItem("✨", listOf("sparkles")),
            EmojiItem("☁️", listOf("cloud")),
            EmojiItem("⛅", listOf("sun behind cloud")),
            EmojiItem("⛈️", listOf("cloud with lightning and rain")),
            EmojiItem("🌤️", listOf("sun behind small cloud")),
            EmojiItem("🌥️", listOf("sun behind large cloud")),
            EmojiItem("🌦️", listOf("sun behind rain cloud")),
            EmojiItem("🌧️", listOf("cloud with rain")),
            EmojiItem("🌨️", listOf("cloud with snow")),
            EmojiItem("🌩️", listOf("cloud with lightning")),
            EmojiItem("🌪️", listOf("tornado")),
            EmojiItem("🌫️", listOf("fog")),
            EmojiItem("🌬️", listOf("wind face")),
            EmojiItem("🌈", listOf("rainbow")),
            EmojiItem("🌂", listOf("closed umbrella")),
            EmojiItem("☂️", listOf("umbrella")),
            EmojiItem("☔", listOf("umbrella with rain drops")),
            EmojiItem("⛱️", listOf("umbrella on ground")),
            EmojiItem("⚡", listOf("high voltage")),
            EmojiItem("❄️", listOf("snowflake")),
            EmojiItem("☃️", listOf("snowman")),
            EmojiItem("⛄", listOf("snowman without snow")),
            EmojiItem("☄️", listOf("comet")),
            EmojiItem("🔥", listOf("fire")),
            EmojiItem("💧", listOf("droplet")),
            EmojiItem("🌊", listOf("water wave"))
        ),
        "Activities" to listOf(
            EmojiItem("🎃", listOf("jack-o-lantern", "halloween")),
            EmojiItem("🎄", listOf("christmas tree")),
            EmojiItem("🎆", listOf("fireworks")),
            EmojiItem("🎇", listOf("sparkler")),
            EmojiItem("🧨", listOf("firecracker")),
            EmojiItem("✨", listOf("sparkles")),
            EmojiItem("🎈", listOf("balloon")),
            EmojiItem("🎉", listOf("party popper")),
            EmojiItem("🎊", listOf("confetti ball")),
            EmojiItem("🎋", listOf("tanabata tree")),
            EmojiItem("🎍", listOf("pine decoration")),
            EmojiItem("🎎", listOf("japanese dolls")),
            EmojiItem("🎏", listOf("carp streamer")),
            EmojiItem("🎐", listOf("wind chime")),
            EmojiItem("🧧", listOf("red envelope")),
            EmojiItem("🎀", listOf("bow")),
            EmojiItem("🎁", listOf("wrapped gift")),
            EmojiItem("🎗️", listOf("reminder ribbon")),
            EmojiItem("🎟️", listOf("admission tickets")),
            EmojiItem("🎫", listOf("ticket")),
            EmojiItem("🎖️", listOf("military medal")),
            EmojiItem("🏆", listOf("trophy")),
            EmojiItem("🏅", listOf("sports medal")),
            EmojiItem("🥇", listOf("1st place medal")),
            EmojiItem("🥈", listOf("2nd place medal")),
            EmojiItem("🥉", listOf("3rd place medal")),
            EmojiItem("⚽", listOf("soccer ball")),
            EmojiItem("⚾", listOf("baseball")),
            EmojiItem("🥎", listOf("softball")),
            EmojiItem("🏀", listOf("basketball")),
            EmojiItem("🏐", listOf("volleyball")),
            EmojiItem("🏈", listOf("american football")),
            EmojiItem("🏉", listOf("rugby football")),
            EmojiItem("🎾", listOf("tennis")),
            EmojiItem("🎳", listOf("bowling")),
            EmojiItem("🏏", listOf("cricket game")),
            EmojiItem("🏑", listOf("field hockey")),
            EmojiItem("🏒", listOf("ice hockey")),
            EmojiItem("🥍", listOf("lacrosse")),
            EmojiItem("🏓", listOf("ping pong")),
            EmojiItem("🏸", listOf("badminton")),
            EmojiItem("🥊", listOf("boxing glove")),
            EmojiItem("🥋", listOf("martial arts uniform")),
            EmojiItem("🥅", listOf("goal net")),
            EmojiItem("⛳", listOf("flag in hole")),
            EmojiItem("⛸️", listOf("ice skate")),
            EmojiItem("🎣", listOf("fishing pole")),
            EmojiItem("🤿", listOf("diving mask")),
            EmojiItem("🎽", listOf("running shirt")),
            EmojiItem("🎿", listOf("skis")),
            EmojiItem("🛷", listOf("sled")),
            EmojiItem("🥌", listOf("curling stone")),
            EmojiItem("🎯", listOf("direct hit")),
            EmojiItem("🪀", listOf("yo-yo")),
            EmojiItem("🪁", listOf("kite")),
            EmojiItem("🎱", listOf("pool 8 ball")),
            EmojiItem("🔮", listOf("crystal ball")),
            EmojiItem("🧿", listOf("nazar amulet")),
            EmojiItem("🎮", listOf("video game")),
            EmojiItem("🕹️", listOf("joystick")),
            EmojiItem("🎰", listOf("slot machine")),
            EmojiItem("🎲", listOf("game die")),
            EmojiItem("🧩", listOf("puzzle piece")),
            EmojiItem("🧸", listOf("teddy bear")),
            EmojiItem("♠️", listOf("spade suit")),
            EmojiItem("♥️", listOf("heart suit")),
            EmojiItem("♦️", listOf("diamond suit")),
            EmojiItem("♣️", listOf("club suit")),
            EmojiItem("♟️", listOf("chess pawn")),
            EmojiItem("🃏", listOf("joker")),
            EmojiItem("🀄", listOf("mahjong red dragon")),
            EmojiItem("🎴", listOf("flower playing cards")),
            EmojiItem("🎭", listOf("performing arts")),
            EmojiItem("🖼️", listOf("framed picture")),
            EmojiItem("🎨", listOf("artist palette")),
            EmojiItem("🧵", listOf("thread")),
            EmojiItem("🧶", listOf("yarn"))
        ),
        "Objects" to listOf(
            EmojiItem("👓", listOf("glasses")),
            EmojiItem("🕶️", listOf("sunglasses")),
            EmojiItem("🥽", listOf("goggles")),
            EmojiItem("🥼", listOf("lab coat")),
            EmojiItem("🦺", listOf("safety vest")),
            EmojiItem("👔", listOf("necktie")),
            EmojiItem("👕", listOf("t-shirt")),
            EmojiItem("👖", listOf("jeans")),
            EmojiItem("🧣", listOf("scarf")),
            EmojiItem("🧤", listOf("gloves")),
            EmojiItem("🧥", listOf("coat")),
            EmojiItem("🧦", listOf("socks")),
            EmojiItem("👗", listOf("dress")),
            EmojiItem("👘", listOf("kimono")),
            EmojiItem("🥻", listOf("sari")),
            EmojiItem("🩱", listOf("one-piece swimsuit")),
            EmojiItem("🩲", listOf("briefs")),
            EmojiItem("🩳", listOf("shorts")),
            EmojiItem("👙", listOf("bikini")),
            EmojiItem("👚", listOf("woman’s clothes")),
            EmojiItem("👛", listOf("purse")),
            EmojiItem("👜", listOf("handbag")),
            EmojiItem("👝", listOf("clutch bag")),
            EmojiItem("🛍️", listOf("shopping bags")),
            EmojiItem("🎒", listOf("backpack")),
            EmojiItem("👞", listOf("man’s shoe")),
            EmojiItem("👟", listOf("running shoe")),
            EmojiItem("🥾", listOf("hiking boot")),
            EmojiItem("🥿", listOf("flat shoe")),
            EmojiItem("👠", listOf("high-heeled shoe")),
            EmojiItem("👡", listOf("woman’s sandal")),
            EmojiItem("👢", listOf("woman’s boot")),
            EmojiItem("👑", listOf("crown")),
            EmojiItem("👒", listOf("woman’s hat")),
            EmojiItem("🎩", listOf("top hat")),
            EmojiItem("🎓", listOf("graduation cap")),
            EmojiItem("🧢", listOf("billed cap")),
            EmojiItem("⛑️", listOf("rescue worker’s helmet")),
            EmojiItem("📿", listOf("prayer beads")),
            EmojiItem("💄", listOf("lipstick")),
            EmojiItem("💍", listOf("ring")),
            EmojiItem("💎", listOf("gem stone")),
            EmojiItem("🔇", listOf("muted speaker")),
            EmojiItem("🔈", listOf("speaker low volume")),
            EmojiItem("🔉", listOf("speaker medium volume")),
            EmojiItem("🔊", listOf("speaker high volume")),
            EmojiItem("📢", listOf("loudspeaker")),
            EmojiItem("📣", listOf("megaphone")),
            EmojiItem("📯", listOf("postal horn")),
            EmojiItem("🔔", listOf("bell")),
            EmojiItem("🔕", listOf("bell with slash")),
            EmojiItem("🎼", listOf("musical score")),
            EmojiItem("🎵", listOf("musical note")),
            EmojiItem("🎶", listOf("musical notes")),
            EmojiItem("🎙️", listOf("studio microphone")),
            EmojiItem("🎚️", listOf("level slider")),
            EmojiItem("🎛️", listOf("control knobs")),
            EmojiItem("🎤", listOf("microphone")),
            EmojiItem("🎧", listOf("headphone")),
            EmojiItem("📻", listOf("radio")),
            EmojiItem("🎷", listOf("saxophone")),
            EmojiItem("🎸", listOf("guitar")),
            EmojiItem("🎹", listOf("musical keyboard")),
            EmojiItem("🎺", listOf("trumpet")),
            EmojiItem("🎻", listOf("violin")),
            EmojiItem("🪕", listOf("banjo")),
            EmojiItem("🥁", listOf("drum")),
            EmojiItem("🪗", listOf("accordion")),
            EmojiItem("📱", listOf("mobile phone")),
            EmojiItem("📲", listOf("mobile phone with arrow")),
            EmojiItem("☎️", listOf("telephone")),
            EmojiItem("📞", listOf("telephone receiver")),
            EmojiItem("📟", listOf("pager")),
            EmojiItem("📠", listOf("fax machine")),
            EmojiItem("🔋", listOf("battery")),
            EmojiItem("🔌", listOf("electric plug")),
            EmojiItem("💻", listOf("laptop")),
            EmojiItem("🖥️", listOf("desktop computer")),
            EmojiItem("🖨️", listOf("printer")),
            EmojiItem("⌨️", listOf("keyboard")),
            EmojiItem("🖱️", listOf("computer mouse")),
            EmojiItem("🖲️", listOf("trackball")),
            EmojiItem("💽", listOf("computer disk")),
            EmojiItem("💾", listOf("floppy disk")),
            EmojiItem("💿", listOf("optical disk")),
            EmojiItem("📀", listOf("dvd")),
            EmojiItem("🧮", listOf("abacus")),
            EmojiItem("🎥", listOf("movie camera")),
            EmojiItem("🎞️", listOf("film frames")),
            EmojiItem("📽️", listOf("film projector")),
            EmojiItem("🎬", listOf("clapper board")),
            EmojiItem("📺", listOf("television")),
            EmojiItem("📷", listOf("camera")),
            EmojiItem("📸", listOf("camera with flash")),
            EmojiItem("📹", listOf("video camera")),
            EmojiItem("📼", listOf("videocassette")),
            EmojiItem("🔍", listOf("magnifying glass tilted left")),
            EmojiItem("🔎", listOf("magnifying glass tilted right")),
            EmojiItem("🕯️", listOf("candle")),
            EmojiItem("💡", listOf("light bulb")),
            EmojiItem("🔦", listOf("flashlight")),
            EmojiItem("🏮", listOf("red paper lantern")),
            EmojiItem("🪔", listOf("diya lamp")),
            EmojiItem("📔", listOf("notebook with decorative cover")),
            EmojiItem("📕", listOf("closed book")),
            EmojiItem("📖", listOf("open book")),
            EmojiItem("📗", listOf("green book")),
            EmojiItem("📘", listOf("blue book")),
            EmojiItem("📙", listOf("orange book")),
            EmojiItem("📚", listOf("books")),
            EmojiItem("📓", listOf("notebook")),
            EmojiItem("📒", listOf("ledger")),
            EmojiItem("📃", listOf("page with curl")),
            EmojiItem("📜", listOf("scroll")),
            EmojiItem("📄", listOf("facing up")),
            EmojiItem("📰", listOf("newspaper")),
            EmojiItem("🗞️", listOf("rolled-up newspaper")),
            EmojiItem("📑", listOf("bookmark tabs")),
            EmojiItem("🔖", listOf("bookmark")),
            EmojiItem("🏷️", listOf("label")),
            EmojiItem("💰", listOf("money bag")),
            EmojiItem("💴", listOf("yen banknote")),
            EmojiItem("💵", listOf("dollar banknote")),
            EmojiItem("💶", listOf("euro banknote")),
            EmojiItem("💷", listOf("pound banknote")),
            EmojiItem("💸", listOf("money with wings")),
            EmojiItem("💳", listOf("credit card")),
            EmojiItem("🧾", listOf("receipt")),
            EmojiItem("💹", listOf("chart increasing with yen")),
            EmojiItem("📧", listOf("e-mail")),
            EmojiItem("📨", listOf("incoming envelope")),
            EmojiItem("📩", listOf("envelope with arrow")),
            EmojiItem("📫", listOf("closed mailbox with raised flag")),
            EmojiItem("📬", listOf("open mailbox with raised flag")),
            EmojiItem("📮", listOf("postbox")),
            EmojiItem("🗳️", listOf("ballot box with ballot")),
            EmojiItem("✏️", listOf("pencil")),
            EmojiItem("✒️", listOf("black nib")),
            EmojiItem("🖋️", listOf("fountain pen")),
            EmojiItem("🖊️", listOf("pen")),
            EmojiItem("🖌️", listOf("paintbrush")),
            EmojiItem("🖍️", listOf("crayon")),
            EmojiItem("📝", listOf("memo")),
            EmojiItem("💼", listOf("briefcase")),
            EmojiItem("📁", listOf("file folder")),
            EmojiItem("📂", listOf("open file folder")),
            EmojiItem("📅", listOf("calendar")),
            EmojiItem("📆", listOf("tear-off calendar")),
            EmojiItem("🗑️", listOf("wastebasket")),
            EmojiItem("🔒", listOf("locked")),
            EmojiItem("🔓", listOf("unlocked")),
            EmojiItem("🔏", listOf("locked with pen")),
            EmojiItem("🔐", listOf("locked with key")),
            EmojiItem("🔑", listOf("key")),
            EmojiItem("🗝️", listOf("old key")),
            EmojiItem("🔨", listOf("hammer")),
            EmojiItem("🪓", listOf("axe")),
            EmojiItem("⛏️", listOf("pick")),
            EmojiItem("⚒️", listOf("hammer and pick")),
            EmojiItem("🛠️", listOf("hammer and wrench")),
            EmojiItem("🗡️", listOf("dagger")),
            EmojiItem("⚔️", listOf("crossed swords")),
            EmojiItem("🔫", listOf("pistol")),
            EmojiItem("🪃", listOf("boomerang")),
            EmojiItem("🏹", listOf("bow and arrow")),
            EmojiItem("🛡️", listOf("shield")),
            EmojiItem("🪚", listOf("carpentry saw")),
            EmojiItem("🔧", listOf("wrench")),
            EmojiItem("🪛", listOf("screwdriver")),
            EmojiItem("🔩", listOf("nut and bolt")),
            EmojiItem("⚙️", listOf("gear")),
            EmojiItem("🗜️", listOf("clamp")),
            EmojiItem("⚖️", listOf("balance scale")),
            EmojiItem("👩‍🦯", listOf("woman with white cane")),
            EmojiItem("👨‍🦯", listOf("man with white cane")),
            EmojiItem("👩‍🦼", listOf("woman in motorized wheelchair")),
            EmojiItem("👨‍🦼", listOf("man in motorized wheelchair")),
            EmojiItem("👩‍🦽", listOf("woman in manual wheelchair")),
            EmojiItem("👨‍🦽", listOf("man in manual wheelchair")),
            EmojiItem("🔗", listOf("link")),
            EmojiItem("⛓️", listOf("chains")),
            EmojiItem("🪝", listOf("hook")),
            EmojiItem("🧰", listOf("toolbox")),
            EmojiItem("🧲", listOf("magnet")),
            EmojiItem("🩸", listOf("drop of blood")),
            EmojiItem("💉", listOf("syringe")),
            EmojiItem("💊", listOf("pill")),
            EmojiItem("🩹", listOf("adhesive bandage")),
            EmojiItem("🩺", listOf("stethoscope")),
            EmojiItem("🚪", listOf("door")),
            EmojiItem("🛗", listOf("elevator")),
            EmojiItem("🪞", listOf("mirror")),
            EmojiItem("🪟", listOf("window")),
            EmojiItem("🛏️", listOf("bed")),
            EmojiItem("🛋️", listOf("couch and lamp")),
            EmojiItem("🪑", listOf("chair")),
            EmojiItem("🚽", listOf("toilet")),
            EmojiItem("🪠", listOf("plunger")),
            EmojiItem("🚿", listOf("shower")),
            EmojiItem("🛀", listOf("person taking bath")),
            EmojiItem("🛁", listOf("bathtub")),
            EmojiItem("🪤", listOf("mouse trap")),
            EmojiItem("🪒", listOf("razor")),
            EmojiItem("🧴", listOf("lotion bottle")),
            EmojiItem("🧷", listOf("safety pin")),
            EmojiItem("🧹", listOf("broom")),
            EmojiItem("🧺", listOf("basket")),
            EmojiItem("🧻", listOf("roll of paper")),
            EmojiItem("🧼", listOf("soap")),
            EmojiItem(" esponja", listOf("sponge")),
            EmojiItem("🪣", listOf("bucket")),
            EmojiItem("🧯", listOf("fire extinguisher")),
            EmojiItem("🛒", listOf("shopping cart")),
            EmojiItem("🚬", listOf("cigarette")),
            EmojiItem("⚰️", listOf("coffin")),
            EmojiItem("🪦", listOf("headstone")),
            EmojiItem("⚱️", listOf("funeral urn")),
            EmojiItem("🧿", listOf("nazar amulet")),
            EmojiItem("🪬", listOf("hamsa")),
            EmojiItem("🗿", listOf("moai"))
        ),
        "Symbols" to listOf(
            EmojiItem("💘", listOf("heart with arrow")),
            EmojiItem("💝", listOf("heart with ribbon")),
            EmojiItem("💖", listOf("sparkling heart")),
            EmojiItem("💗", listOf("growing heart")),
            EmojiItem("💓", listOf("beating heart")),
            EmojiItem("💞", listOf("revolving hearts")),
            EmojiItem("💕", listOf("two hearts")),
            EmojiItem("💟", listOf("heart decoration")),
            EmojiItem("❣️", listOf("heavy heart exclamation")),
            EmojiItem("💔", listOf("broken heart")),
            EmojiItem("❤️‍🔥", listOf("heart on fire")),
            EmojiItem("❤️‍🩹", listOf("mending heart")),
            EmojiItem("❤️", listOf("red heart")),
            EmojiItem("🧡", listOf("orange heart")),
            EmojiItem("💛", listOf("yellow heart")),
            EmojiItem("💚", listOf("green heart")),
            EmojiItem("💙", listOf("blue heart")),
            EmojiItem("💜", listOf("purple heart")),
            EmojiItem("🤎", listOf("brown heart")),
            EmojiItem("🖤", listOf("black heart")),
            EmojiItem("🤍", listOf("white heart")),
            EmojiItem("💋", listOf("kiss mark")),
            EmojiItem("💯", listOf("hundred points")),
            EmojiItem("💢", listOf("anger symbol")),
            EmojiItem("💥", listOf("collision")),
            EmojiItem("💫", listOf("dizzy")),
            EmojiItem("💦", listOf("sweat droplets")),
            EmojiItem("💨", listOf("dash")),
            EmojiItem("🕳️", listOf("hole")),
            EmojiItem("💣", listOf("bomb")),
            EmojiItem("💬", listOf("speech balloon")),
            EmojiItem("👁️‍🗨️", listOf("eye in speech bubble")),
            EmojiItem("🗨️", listOf("left speech bubble")),
            EmojiItem("🗯️", listOf("right anger bubble")),
            EmojiItem("💭", listOf("thought balloon")),
            EmojiItem("💤", listOf("zzz")),
            EmojiItem("👋", listOf("wave")),
            EmojiItem("🖐️", listOf("raised hand")),
            EmojiItem("✋", listOf("raised hand")),
            EmojiItem("🖖", listOf("vulcan salute")),
            EmojiItem("👌", listOf("ok hand")),
            EmojiItem("🤌", listOf("pinched fingers")),
            EmojiItem("🤏", listOf("pinched hand")),
            EmojiItem("✌️", listOf("victory hand")),
            EmojiItem("🤞", listOf("crossed fingers")),
            EmojiItem("🤟", listOf("love-you gesture")),
            EmojiItem("🤘", listOf("sign of the horns")),
            EmojiItem("🤙", listOf("call me hand")),
            EmojiItem("👈", listOf("backhand index pointing left")),
            EmojiItem("👉", listOf("backhand index pointing right")),
            EmojiItem("👆", listOf("backhand index pointing up")),
            EmojiItem("🖕", listOf("middle finger")),
            EmojiItem("👇", listOf("backhand index pointing down")),
            EmojiItem("☝️", listOf("index pointing up")),
            EmojiItem("👍", listOf("thumbs up")),
            EmojiItem("👎", listOf("thumbs down")),
            EmojiItem("✊", listOf("raised fist")),
            EmojiItem("👊", listOf("oncoming fist")),
            EmojiItem("🤛", listOf("left-facing fist")),
            EmojiItem("🤜", listOf("right-facing fist")),
            EmojiItem("👏", listOf("clapping hands")),
            EmojiItem("🙌", listOf("raising hands")),
            EmojiItem("👐", listOf("open hands")),
            EmojiItem("🤲", listOf("palms up together")),
            EmojiItem("🤝", listOf("handshake")),
            EmojiItem("🙏", listOf("folded hands")),
            EmojiItem("✍️", listOf("writing hand")),
            EmojiItem("💅", listOf("nail polish")),
            EmojiItem("🤳", listOf("selfie")),
            EmojiItem("💪", listOf("flexed biceps")),
            EmojiItem("🦾", listOf("mechanical arm")),
            EmojiItem("🦿", listOf("mechanical leg")),
            EmojiItem("🦵", listOf("leg")),
            EmojiItem("🦶", listOf("foot")),
            EmojiItem("👂", listOf("ear")),
            EmojiItem("🦻", listOf("ear with hearing aid")),
            EmojiItem("👃", listOf("nose")),
            EmojiItem("🧠", listOf("brain")),
            EmojiItem("🫀", listOf("anatomical heart")),
            EmojiItem("🫁", listOf("lungs")),
            EmojiItem("🦷", listOf("tooth")),
            EmojiItem("🦴", listOf("bone")),
            EmojiItem("👀", listOf("eyes")),
            EmojiItem("👁️", listOf("eye")),
            EmojiItem("👅", listOf("tongue")),
            EmojiItem("👄", listOf("mouth"))
        ),
        "Flags" to listOf(
            EmojiItem("🏁", listOf("chequered flag")),
            EmojiItem("🚩", listOf("triangular flag")),
            EmojiItem("🎌", listOf("crossed flags")),
            EmojiItem("🏴", listOf("black flag")),
            EmojiItem("🏳️", listOf("white flag")),
            EmojiItem("🏳️‍🌈", listOf("rainbow flag")),
            EmojiItem("🏳️‍⚧️", listOf("transgender flag")),
            EmojiItem("🏴‍☠️", listOf("pirate flag")),
            EmojiItem("🇮🇳", listOf("india", "flag")),
            EmojiItem("🇺🇸", listOf("united states", "flag")),
            EmojiItem("🇬🇧", listOf("united kingdom", "flag")),
            EmojiItem("🇨🇦", listOf("canada", "flag")),
            EmojiItem("🇦🇺", listOf("australia", "flag")),
            EmojiItem("🇩🇪", listOf("germany", "flag")),
            EmojiItem("🇫🇷", listOf("france", "flag")),
            EmojiItem("🇯🇵", listOf("japan", "flag")),
            EmojiItem("🇰🇷", listOf("south korea", "flag")),
            EmojiItem("🇨🇳", listOf("china", "flag")),
            EmojiItem("🇧🇷", listOf("brazil", "flag")),
            EmojiItem("🇷🇺", listOf("russia", "flag")),
            EmojiItem("🇪🇸", listOf("spain", "flag")),
            EmojiItem("🇮🇹", listOf("italy", "flag")),
            EmojiItem("🇲🇽", listOf("mexico", "flag")),
            EmojiItem("🇿🇦", listOf("south africa", "flag")),
            EmojiItem("🇸🇦", listOf("saudi arabia", "flag")),
            EmojiItem("🇦🇪", listOf("united arab emirates", "flag")),
            EmojiItem("🇸🇬", listOf("singapore", "flag")),
            EmojiItem("🇳🇱", listOf("netherlands", "flag")),
            EmojiItem("🇸🇪", listOf("sweden", "flag")),
            EmojiItem("🇳🇴", listOf("norway", "flag")),
            EmojiItem("🇩🇰", listOf("denmark", "flag")),
            EmojiItem("🇫🇮", listOf("finland", "flag")),
            EmojiItem("🇵🇭", listOf("philippines", "flag")),
            EmojiItem("🇮🇩", listOf("indonesia", "flag")),
            EmojiItem("🇲🇾", listOf("malaysia", "flag")),
            EmojiItem("🇹🇭", listOf("thailand", "flag")),
            EmojiItem("🇻🇳", listOf("vietnam", "flag")),
            EmojiItem("🇳🇿", listOf("new zealand", "flag")),
            EmojiItem("🇮🇱", listOf("israel", "flag")),
            EmojiItem("🇪🇬", listOf("egypt", "flag")),
            EmojiItem("🇳🇬", listOf("nigeria", "flag")),
            EmojiItem("🇦🇷", listOf("argentina", "flag")),
            EmojiItem("🇨🇱", listOf("chile", "flag")),
            EmojiItem("🇨🇴", listOf("colombia", "flag")),
            EmojiItem("🇵🇪", listOf("peru", "flag")),
            EmojiItem("🇵🇰", listOf("pakistan", "flag")),
            EmojiItem("🇧🇩", listOf("bangladesh", "flag")),
            EmojiItem("🇺🇦", listOf("ukraine", "flag")),
            EmojiItem("🇵🇱", listOf("poland", "flag")),
            EmojiItem("🇧🇪", listOf("belgium", "flag")),
            EmojiItem("🇨🇭", listOf("switzerland", "flag")),
            EmojiItem("🇦🇹", listOf("austria", "flag")),
            EmojiItem("🇮🇪", listOf("ireland", "flag")),
            EmojiItem("🇵🇹", listOf("portugal", "flag")),
            EmojiItem("🇬🇷", listOf("greece", "flag")),
            EmojiItem("🇹🇷", listOf("turkey", "flag"))
        )
    )
}
